#pragma once

#define CINDER_REMAINING_MIP_LEVELS		  ( 0xFFFFFFFF )
#define CINDER_REMAINING_ARRAY_LAYERS	  ( 0xFFFFFFFF )
#define CINDER_MAX_BOUND_DESCRIPTOR_SETS  32
#define CINDER_MAX_PUSH_CONSTANT_RANGES	  64
#define CINDER_MAX_VERTEX_INPUTS		  32
#define CINDER_VERTEX_ATTRIBUTE_UNUSED	  ( ~0 )
#define CINDER_APPEND_VERTEX_LOCATION	  ( ~0 )
#define CINDER_APPEND_VERTEX_OFFSET		  ( ~0 )
#define CINDER_MAX_RENDER_TARGETS		  8
#define CINDER_DEFAULT_DEPTH			  ( 1.0f )
#define CINDER_DEFAULT_DEPTH_BIAS		  ( 0.0f )
#define CINDER_DEFAULT_DEPTH_BIAS_CLAMP	  ( 0.0f )
#define CINDER_DEFAULT_DEPTH_BIAS_SCALE	  ( 0.0f )
#define CINDER_DEFAULT_LINE_WIDTH		  ( 1.0f )
#define CINDER_DEFAULT_STENCIL			  ( 0xFF )
#define CINDER_DEFAULT_STENCIL_READ_MASK  ( 0xFF )
#define CINDER_DEFAULT_STENCIL_WRITE_MASK ( 0xFF )
#define CINDER_DEFAULT_STENCIL_REFERENCE  ( 0 )
#define CINDER_DEFAULT_SAMPLE_SHADING	  ( 1.0f )
#define CINDER_DEFAULT_VIEWPORT_MIN_DEPTH ( 0.0f )
#define CINDER_DEFAULT_VIEWPORT_MAX_DEPTH ( 1.0f )
#define CINDER_DEFAULT_BLEND_R			  ( 1.0f )
#define CINDER_DEFAULT_BLEND_G			  ( 1.0f )
#define CINDER_DEFAULT_BLEND_B			  ( 1.0f )
#define CINDER_DEFAULT_BLEND_A			  ( 1.0f )

/////////////////////////////////////////////////////////////////////////////////
// Context Constants

/*
#define CINDER_CONTEXT_MAX_TEXTURE_COUNT 128 // Combined image/samplers
#define CINDER_CONTEXT_MAX_UBO_COUNT	 32	 // Uniform buffer blocks
#define CINDER_CONTEXT_MAX_IMAGE_COUNT	 128 // Images
#define CINDER_CONTEXT_MAX_SAMPLER_COUNT 16	 // Samplers
#define CINDER_CONTEXT_MAX_SSBO_COUNT	 32	 // Storage buffer blocks
#define CINDER_CONTEXT_MAX_UAV_COUNT	 16	 // Unordered access views
*/

#define CINDER_CONTEXT_PER_STAGE_TEXTURE_COUNT 64 // Combined image/samplers
#define CINDER_CONTEXT_PER_STAGE_UBO_COUNT	   64 // Uniform buffer blocks
#define CINDER_CONTEXT_PER_STAGE_IMAGE_COUNT   64 // Images
#define CINDER_CONTEXT_PER_STAGE_SAMPLER_COUNT 32 // Samplers
#define CINDER_CONTEXT_PER_STAGE_SSBO_COUNT	   32 // Storage buffer blocks
#define CINDER_CONTEXT_PER_STAGE_UAV_COUNT	   16 // Unordered access views

#define CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE 0
#define CINDER_CONTEXT_PER_STAGE_OFFSET_UBO		( CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE + CINDER_CONTEXT_PER_STAGE_TEXTURE_COUNT )
#define CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE	( CINDER_CONTEXT_PER_STAGE_OFFSET_UBO + CINDER_CONTEXT_PER_STAGE_UBO_COUNT )
#define CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER ( CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE + CINDER_CONTEXT_PER_STAGE_IMAGE_COUNT )
#define CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO	( CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER + CINDER_CONTEXT_PER_STAGE_SAMPLER_COUNT )
#define CINDER_CONTEXT_PER_STAGE_OFFSET_UAV		( CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO + CINDER_CONTEXT_PER_STAGE_SSBO_COUNT )

#define CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT \
	( CINDER_CONTEXT_PER_STAGE_TEXTURE_COUNT +  \
	  CINDER_CONTEXT_PER_STAGE_UBO_COUNT +      \
	  CINDER_CONTEXT_PER_STAGE_IMAGE_COUNT +    \
	  CINDER_CONTEXT_PER_STAGE_SAMPLER_COUNT +  \
	  CINDER_CONTEXT_PER_STAGE_SSBO_COUNT +     \
	  CINDER_CONTEXT_PER_STAGE_UAV_COUNT )

#define CINDER_CONTEXT_STAGE_INDEX_VS 0
#define CINDER_CONTEXT_STAGE_INDEX_PS 1
#define CINDER_CONTEXT_STAGE_INDEX_HS 2
#define CINDER_CONTEXT_STAGE_INDEX_DS 3
#define CINDER_CONTEXT_STAGE_INDEX_GS 4
#define CINDER_CONTEXT_STAGE_COUNT	  5

#define CINDER_CONTEXT_STAGE_SHIFT_START_VS ( CINDER_CONTEXT_STAGE_INDEX_VS * CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT )
#define CINDER_CONTEXT_STAGE_SHIFT_START_PS ( CINDER_CONTEXT_STAGE_INDEX_PS * CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT )
#define CINDER_CONTEXT_STAGE_SHIFT_START_HS ( CINDER_CONTEXT_STAGE_INDEX_HS * CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT )
#define CINDER_CONTEXT_STAGE_SHIFT_START_DS ( CINDER_CONTEXT_STAGE_INDEX_DS * CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT )
#define CINDER_CONTEXT_STAGE_SHIFT_START_GS ( CINDER_CONTEXT_STAGE_INDEX_GS * CINDER_CONTEXT_WHOLE_STAGE_SHIFT_AMOUNT )

#define CINDER_CONTEXT_VS_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE )
#define CINDER_CONTEXT_VS_BINDING_SHIFT_UBO		( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_UBO )
#define CINDER_CONTEXT_VS_BINDING_SHIFT_IMAGE	( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE )
#define CINDER_CONTEXT_VS_BINDING_SHIFT_SAMPLER ( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER )
#define CINDER_CONTEXT_VS_BINDING_SHIFT_SSBO	( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO )
#define CINDER_CONTEXT_VS_BINDING_SHIFT_UAV		( CINDER_CONTEXT_STAGE_SHIFT_START_VS + CINDER_CONTEXT_PER_STAGE_OFFSET_UAV )

#define CINDER_CONTEXT_PS_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE )
#define CINDER_CONTEXT_PS_BINDING_SHIFT_UBO		( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_UBO )
#define CINDER_CONTEXT_PS_BINDING_SHIFT_IMAGE	( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE )
#define CINDER_CONTEXT_PS_BINDING_SHIFT_SAMPLER ( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER )
#define CINDER_CONTEXT_PS_BINDING_SHIFT_SSBO	( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO )
#define CINDER_CONTEXT_PS_BINDING_SHIFT_UAV		( CINDER_CONTEXT_STAGE_SHIFT_START_PS + CINDER_CONTEXT_PER_STAGE_OFFSET_UAV )

#define CINDER_CONTEXT_HS_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE )
#define CINDER_CONTEXT_HS_BINDING_SHIFT_UBO		( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_UBO )
#define CINDER_CONTEXT_HS_BINDING_SHIFT_IMAGE	( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE )
#define CINDER_CONTEXT_HS_BINDING_SHIFT_SAMPLER ( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER )
#define CINDER_CONTEXT_HS_BINDING_SHIFT_SSBO	( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO )
#define CINDER_CONTEXT_HS_BINDING_SHIFT_UAV		( CINDER_CONTEXT_STAGE_SHIFT_START_HS + CINDER_CONTEXT_PER_STAGE_OFFSET_UAV )

#define CINDER_CONTEXT_DS_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE )
#define CINDER_CONTEXT_DS_BINDING_SHIFT_UBO		( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_UBO )
#define CINDER_CONTEXT_DS_BINDING_SHIFT_IMAGE	( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE )
#define CINDER_CONTEXT_DS_BINDING_SHIFT_SAMPLER ( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER )
#define CINDER_CONTEXT_DS_BINDING_SHIFT_SSBO	( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO )
#define CINDER_CONTEXT_DS_BINDING_SHIFT_UAV		( CINDER_CONTEXT_STAGE_SHIFT_START_DS + CINDER_CONTEXT_PER_STAGE_OFFSET_UAV )

#define CINDER_CONTEXT_GS_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_TEXTURE )
#define CINDER_CONTEXT_GS_BINDING_SHIFT_UBO		( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_UBO )
#define CINDER_CONTEXT_GS_BINDING_SHIFT_IMAGE	( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_IMAGE )
#define CINDER_CONTEXT_GS_BINDING_SHIFT_SAMPLER ( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_SAMPLER )
#define CINDER_CONTEXT_GS_BINDING_SHIFT_SSBO	( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_SSBO )
#define CINDER_CONTEXT_GS_BINDING_SHIFT_UAV		( CINDER_CONTEXT_STAGE_SHIFT_START_GS + CINDER_CONTEXT_PER_STAGE_OFFSET_UAV )

//#define CINDER_CONTEXT_BINDING_SHIFT_SAMPLER 0
//#define CINDER_CONTEXT_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_BINDING_SHIFT_SAMPLER + CINDER_CONTEXT_MAX_SAMPLER_COUNT )
//#define CINDER_CONTEXT_BINDING_SHIFT_IMAGE	 ( CINDER_CONTEXT_BINDING_SHIFT_TEXTURE + CINDER_CONTEXT_MAX_TEXTURE_COUNT )
//#define CINDER_CONTEXT_BINDING_SHIFT_UBO	 ( CINDER_CONTEXT_BINDING_SHIFT_IMAGE + CINDER_CONTEXT_MAX_IMAGE_COUNT )
//#define CINDER_CONTEXT_BINDING_SHIFT_SSBO	 ( CINDER_CONTEXT_BINDING_SHIFT_UBO + CINDER_CONTEXT_MAX_UBO_COUNT )
//#define CINDER_CONTEXT_BINDING_SHIFT_UAV	 ( CINDER_CONTEXT_BINDING_SHIFT_SSBO + CINDER_CONTEXT_MAX_SSBO_COUNT )
