#pragma once

#define CINDER_REMAINING_MIP_LEVELS			 ( 0xFFFFFFFF )
#define CINDER_REMAINING_ARRAY_LAYERS		 ( 0xFFFFFFFF )
#define CINDER_MAX_BOUND_DESCRIPTOR_SETS	 32
#define CINDER_MAX_PUSH_CONSTANT_RANGES		 64
#define CINDER_MAX_VERTEX_INPUTS			 32
#define CINDER_VERTEX_ATTRIBUTE_UNUSED		 ( ~0 )
#define CINDER_APPEND_VERTEX_LOCATION		 ( ~0 )
#define CINDER_APPEND_VERTEX_OFFSET			 ( ~0 )
#define CINDER_MAX_RENDER_TARGETS			 8
#define CINDER_DEFAULT_DEPTH				 ( 0.0f )
#define CINDER_DEFAULT_DEPTH_BIAS			 ( 0.0f )
#define CINDER_DEFAULT_DEPTH_BIAS_CLAMP		 ( 0.0f )
#define CINDER_DEFAULT_DEPTH_BIAS_SCALE		 ( 0.0f )
#define CINDER_DEFAULT_LINE_WIDTH			 ( 1.0f )
#define CINDER_DEFAULT_STENCIL				 ( 0xFF )
#define CINDER_DEFAULT_STENCIL_READ_MASK	 ( 0xFF )
#define CINDER_DEFAULT_STENCIL_WRITE_MASK	 ( 0xFF )
#define CINDER_DEFAULT_STENCIL_REFERENCE	 ( 0 )
#define CINDER_DEFAULT_SAMPLE_SHADING		 ( 1.0f )
#define CINDER_DEFAULT_VIEWPORT_MIN_DEPTH	 ( 0.0f )
#define CINDER_DEFAULT_VIEWPORT_MAX_DEPTH	 ( 1.0f )
#define CINDER_DEFAULT_BLEND_R				 ( 1.0f )
#define CINDER_DEFAULT_BLEND_G				 ( 1.0f )
#define CINDER_DEFAULT_BLEND_B				 ( 1.0f )
#define CINDER_DEFAULT_BLEND_A				 ( 1.0f )
#define CINDER_CONTEXT_MAX_SAMPLER_COUNT	 128
#define CINDER_CONTEXT_MAX_TEXTURE_COUNT	 128
#define CINDER_CONTEXT_MAX_IMAGE_COUNT		 128
#define CINDER_CONTEXT_MAX_UBO_COUNT		 128
#define CINDER_CONTEXT_MAX_SSBO_COUNT		 128
#define CINDER_CONTEXT_MAX_UAV_COUNT		 128
#define CINDER_CONTEXT_BINDING_SHIFT_SAMPLER 0
#define CINDER_CONTEXT_BINDING_SHIFT_TEXTURE ( CINDER_CONTEXT_BINDING_SHIFT_SAMPLER + CINDER_CONTEXT_MAX_SAMPLER_COUNT )
#define CINDER_CONTEXT_BINDING_SHIFT_IMAGE	 ( CINDER_CONTEXT_BINDING_SHIFT_TEXTURE + CINDER_CONTEXT_MAX_TEXTURE_COUNT )
#define CINDER_CONTEXT_BINDING_SHIFT_UBO	 ( CINDER_CONTEXT_BINDING_SHIFT_IMAGE + CINDER_CONTEXT_MAX_IMAGE_COUNT )
#define CINDER_CONTEXT_BINDING_SHIFT_SSBO	 ( CINDER_CONTEXT_BINDING_SHIFT_UBO + CINDER_CONTEXT_MAX_UBO_COUNT )
#define CINDER_CONTEXT_BINDING_SHIFT_UAV	 ( CINDER_CONTEXT_BINDING_SHIFT_SSBO + CINDER_CONTEXT_MAX_SSBO_COUNT )
#define CINDER_INVALID_SEMAPHORE_VALUE		 ( (uint64_t)~0 )
